### ISSUE TITLE
Jellyplayer softlocks on opening some anime

### ISSUE THREAD

**Issue by sonicjhon1** [prayag17/JellyPlayer#206]
**Describe the bug**
Clicking on some anime will make Jellyplayer stuck on a purple screen, an error is then shown in the Console.
![image](https://github.com/prayag17/JellyPlayer/assets/41381685/52c9c99e-e223-4d77-bc5c-ad3af5b45494)
```javascript
index-b123aab0.js:40  TypeError: Cannot read properties of undefined (reading 'Name')
    at Kne (index-b123aab0.js:339:112073)
    at sb (index-b123aab0.js:38:19538)
    at lv (index-b123aab0.js:40:3139)
    at jR (index-b123aab0.js:40:44817)
    at ER (index-b123aab0.js:40:39774)
    at h$ (index-b123aab0.js:40:39702)
    at lp (index-b123aab0.js:40:39555)
    at bv (index-b123aab0.js:40:35920)
    at Mw (index-b123aab0.js:40:36724)
    at is (index-b123aab0.js:38:3279)
av @ index-b123aab0.js:40
index-b123aab0.js:38  Uncaught TypeError: Cannot read properties of undefined (reading 'Name')
    at Kne (index-b123aab0.js:339:112073)
    at sb (index-b123aab0.js:38:19538)
    at lv (index-b123aab0.js:40:3139)
    at jR (index-b123aab0.js:40:44817)
    at ER (index-b123aab0.js:40:39774)
    at h$ (index-b123aab0.js:40:39702)
    at lp (index-b123aab0.js:40:39555)
    at bv (index-b123aab0.js:40:35920)
    at Mw (index-b123aab0.js:40:36724)
    at is (index-b123aab0.js:38:3279)
```
Although other anime do work fine.

**To Reproduce**
1. Open JellyPlayer
2. Click on "Reign of the Seven Spellblades" or some other certain anime
3. Purple screen

Alternate Steps to reproduce the behavior:
1. Open JellyPlayer
2. Click on More Info on "Reign of the Seven Spellblades" banner
3. Purple screen

**Expected behavior**
Should show a simillar screen:
![image](https://github.com/prayag17/JellyPlayer/assets/41381685/f75f0ca1-5dd0-48b5-ae53-411b0fd197f6)

**Screenshots**
https://github.com/prayag17/JellyPlayer/assets/41381685/9b92fe4c-6ee0-4f8b-b264-8735998715e9
(Manually reopened JellyPlayer when its stuck at purple screen)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Alpha 2

**Additional context**
Tried opening the broken anime shows in Jellyfin, Jelly Vue, Findroid. All of them worked as expected.
All of these anime are broken
![image](https://github.com/prayag17/JellyPlayer/assets/41381685/bb9e9977-1728-40e3-9c12-8f6d7f300ce6)
Meanwhile these anime are working:
- Protocol: Rain
- TenPuru
- The Dreaming Boy is a Realist

**Comment by prayag17** [comment]
Is this issue fixed with https://github.com/prayag17/JellyPlayer/releases/v0.0.1 ?

**Comment by sonicjhon1** [comment]
> Is this issue fixed with https://github.com/prayag17/JellyPlayer/releases/latest ?

Sorry for the late reply, yes it works now. No more softlocks 😄
Thank you❤️
